export const allRoles = [
  'an engineer',
  'a photographer',
  'a software engineer',
  'a fullstack engineer',
  'a Python apologist',
  'a RoR aficionado',
  'an app developer',
  'a mentor',
  'a teacher',
  'a student',
  'a friend',
  'a cook',
  'a reviewer',
  'a traveller',
  'an explorer',
  'a nerd',
  'a geek',
];
